version: '3'

services:
  cassandra:
    image: bitnami/cassandra:latest
    ports:
      - '9042:9042'
    environment:
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - ./data/cassandra:/var/lib/cassandra

volumes:
  cassandra_data:
    driver: local