feign:
  client:
    config:
      covid:
        api:
          url: https://covid-193.p.rapidapi.com
          retry-max-attempts: 5

logging:
  level:
    dev:
      drewboiii:
        healthstatsserviceapi:
          client: DEBUG
