spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    cache-names: CacheableApplicationRepository
    caffeine:
      spec: maximumSize=10,expireAfterWrite=10m,recordStats
    today-stats-cache: maximumSize=10,expireAfterWrite=1d,recordStats
    covid-countries-cache: maximumSize=10,expireAfterWrite=7d,recordStats
    covid-today-stats-cache: maximumSize=10,expireAfterWrite=1d,recordStats
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    keyspace-name: ${CASSANDRA_KEYSPACE}
    contact-points: ${CASSANDRA_CONTACT_POINTS}
    port: ${CASSANDRA_PORT}
    local-datacenter: ${CASSANDRA_LOCAL_DC}
    connection:
      connect-timeout: 60s
      init-query-timeout: 60s
    request:
      timeout: 60s

application:
  cache:
    enabled: true
  client:
    interceptor:
      covid19:
        api-key: ${HEALTH_STATS_SERVICE_APIKEY}
        api-host: ${HEALTH_STATS_SERVICE_APIHOST}

feign:
  client:
    config:
      covid:
        api:
          url: ${COVID_CLIENT_URL}
          retry-max-attempts: 5
