spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    cache-names: CacheableApplicationRepository
    caffeine:
      spec: maximumSize=10,expireAfterWrite=10m,recordStats
    today-stats-cache: maximumSize=10,expireAfterWrite=1d,recordStats
    covid-countries-cache: maximumSize=10,expireAfterWrite=7d,recordStats
    covid-today-stats-cache: maximumSize=10,expireAfterWrite=1d,recordStats
    hiv-countries-cache: maximumSize=10,expireAfterWrite=7d,recordStats
    hiv-today-stats-cache: maximumSize=10,expireAfterWrite=1d,recordStats
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    keyspace-name: ${CASSANDRA_KEYSPACE}
    contact-points: ${CASSANDRA_CONTACT_POINTS}
    port: ${CASSANDRA_PORT}
    local-datacenter: ${CASSANDRA_LOCAL_DC}
    connection:
      connect-timeout: 60s
      init-query-timeout: 60s
    request:
      timeout: 60s
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration
      - org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.KafkaMetricsAutoConfiguration

application:
  name: health-stats-service-api
  cache:
    enabled: true
  cassandra:
    enabled: true
  client:
    interceptor:
      covid19:
        api-key: ${HEALTH_STATS_SERVICE_APIKEY}
        api-host: ${HEALTH_STATS_SERVICE_APIHOST}
  kafka:
    enabled: true
    server: ${KAFKA_SERVER}
    topic:
      logs: ${SERVER_LOG_TOPIC}

feign:
  client:
    config:
      covid:
        api:
          url: ${COVID_CLIENT_URL}
          retry-max-attempts: 5
      hiv:
        api:
          url: ${HIV_CLIENT_URL}
          retry-max-attempts: 5

management:
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 10
      failureRateThreshold: 10
      slowCallRateThreshold: 20
      slowCallDurationThreshold: 100ms
      registerHealthIndicator: true
    instances:
      hiv:
        baseConfig: default
      covid:
        baseConfig: default

springdoc:
  swagger-ui:
    enabled: false
