package dev.drewboiii.hivworldwidestatsmock.service

import dev.drewboiii.hivworldwidestatsmock.dto.CountriesResponse
import dev.drewboiii.hivworldwidestatsmock.dto.Statistics
import dev.drewboiii.hivworldwidestatsmock.dto.StatsResponse
import org.springframework.stereotype.Service
import java.time.LocalDateTime
import kotlin.math.abs
import kotlin.math.roundToInt
import kotlin.math.roundToLong
import kotlin.random.Random

@Service
class StatsService {
    fun getTodayStats(countryName: String): StatsResponse = buildStatsResponse(countryName)

    fun getCountries(): CountriesResponse =
        CountriesResponse(
            countries = countries,
            quantity = countries.size
        )

    private fun buildStatsResponse(countryName: String): StatsResponse {
        if (!countries.map { it.lowercase() }.contains(countryName.lowercase())) {
            return StatsResponse(statistics = emptyList())
        }

        val statistics = listOf(
            Statistics(
                country = Statistics.Country(
                    name = countryName,
                    continent = null,
                    population = abs(Random(Long.MAX_VALUE).nextLong(1_000_000_000))
                ),
                date = LocalDateTime.now(),
                cases = Statistics.Cases(
                    new = Statistics.Cases.NewCases(
                        discovered = abs(Random(Long.MAX_VALUE).nextLong(100_000)),
                        lethal = abs(Random(Long.MAX_VALUE).nextLong(1_000)),
                        active = abs(Random(Long.MAX_VALUE).nextLong(1_000_000)),
                        recovered = abs(Random(Long.MAX_VALUE).nextLong(100_000_000))
                    ),
                    dead = Statistics.Cases.DeadCases(
                        lethal = abs(Random(Long.MAX_VALUE).nextLong(100_000))
                    ),
                    cured = Statistics.Cases.CuredCases(
                        totalRecovered = abs(Random(Long.MAX_VALUE).nextLong(100_000_000))
                    )
                )
            )
        )

        return StatsResponse(statistics = statistics)
    }
    companion object {
        val countries: Set<String> = setOf(
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Anguilla",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia-and-Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina-Faso",
            "Burundi",
            "Cabo-Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "CAR",
            "Cayman-Islands",
            "Chad",
            "Channel-Islands",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "Costa-Rica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czechia",
            "Denmark",
            "Diamond-Princess",
            "Djibouti",
            "Dominica",
            "Dominican-Republic",
            "DPRK",
            "DRC",
            "Ecuador",
            "Egypt",
            "El-Salvador",
            "Equatorial-Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Faeroe-Islands",
            "Falkland-Islands",
            "Fiji",
            "Finland",
            "France",
            "French-Guiana",
            "French-Polynesia",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hong-Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle-of-Man",
            "Israel",
            "Italy",
            "Ivory-Coast",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macao",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New-Caledonia",
            "New-Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "North-Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua-New-Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "R&eacute;union",
            "Romania",
            "Russia",
            "Rwanda",
            "S-Korea",
            "Saint-Helena",
            "Saint-Kitts-and-Nevis",
            "Saint-Lucia",
            "Saint-Martin",
            "Saint-Pierre-Miquelon",
            "Samoa",
            "San-Marino",
            "Sao-Tome-and-Principe",
            "Saudi-Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra-Leone",
            "Singapore",
            "Sint-Maarten",
            "Slovakia",
            "Slovenia",
            "Solomon-Islands",
            "Somalia",
            "South-Africa",
            "South-Sudan",
            "Spain",
            "Sri-Lanka",
            "St-Barth",
            "St-Vincent-Grenadines",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad-and-Tobago",
            "Tunisia",
            "Turkey",
            "Turks-and-Caicos",
            "Tuvalu",
            "UAE",
            "Uganda",
            "UK",
            "Ukraine",
            "Uruguay",
            "USA",
            "Uzbekistan",
            "Vanuatu",
            "Vatican-City",
            "Venezuela",
            "Vietnam",
            "Western-Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        )
    }
//    private fun countries() = listOf(
//        "Afghanistan",
//        "Albania",
//        "Algeria",
//        "Andorra",
//        "Angola",
//        "Anguilla",
//        "Argentina",
//        "Armenia",
//        "Aruba",
//        "Australia",
//        "Austria",
//        "Azerbaijan",
//        "Bahamas",
//        "Bahrain",
//        "Bangladesh",
//        "Barbados",
//        "Belarus",
//        "Belgium",
//        "Belize",
//        "Benin",
//        "Bermuda",
//        "Bhutan",
//        "Bolivia",
//        "Bosnia-and-Herzegovina",
//        "Botswana",
//        "Brazil",
//        "Brunei",
//        "Bulgaria",
//        "Burkina-Faso",
//        "Burundi",
//        "Cabo-Verde",
//        "Cambodia",
//        "Cameroon",
//        "Canada",
//        "CAR",
//        "Cayman-Islands",
//        "Chad",
//        "Channel-Islands",
//        "Chile",
//        "China",
//        "Colombia",
//        "Comoros",
//        "Congo",
//        "Costa-Rica",
//        "Croatia",
//        "Cuba",
//        "Cyprus",
//        "Czechia",
//        "Denmark",
//        "Diamond-Princess",
//        "Djibouti",
//        "Dominica",
//        "Dominican-Republic",
//        "DPRK",
//        "DRC",
//        "Ecuador",
//        "Egypt",
//        "El-Salvador",
//        "Equatorial-Guinea",
//        "Eritrea",
//        "Estonia",
//        "Eswatini",
//        "Ethiopia",
//        "Faeroe-Islands",
//        "Falkland-Islands",
//        "Fiji",
//        "Finland",
//        "France",
//        "French-Guiana",
//        "French-Polynesia",
//        "Gabon",
//        "Gambia",
//        "Georgia",
//        "Germany",
//        "Ghana",
//        "Gibraltar",
//        "Greece",
//        "Greenland",
//        "Grenada",
//        "Guadeloupe",
//        "Guatemala",
//        "Guinea",
//        "Guinea-Bissau",
//        "Guyana",
//        "Haiti",
//        "Honduras",
//        "Hong-Kong",
//        "Hungary",
//        "Iceland",
//        "India",
//        "Indonesia",
//        "Iran",
//        "Iraq",
//        "Ireland",
//        "Isle-of-Man",
//        "Israel",
//        "Italy",
//        "Ivory-Coast",
//        "Jamaica",
//        "Japan",
//        "Jordan",
//        "Kazakhstan",
//        "Kenya",
//        "Kiribati",
//        "Kuwait",
//        "Kyrgyzstan",
//        "Laos",
//        "Latvia",
//        "Lebanon",
//        "Lesotho",
//        "Liberia",
//        "Libya",
//        "Liechtenstein",
//        "Lithuania",
//        "Luxembourg",
//        "Macao",
//        "Madagascar",
//        "Malawi",
//        "Malaysia",
//        "Maldives",
//        "Mali",
//        "Malta",
//        "Martinique",
//        "Mauritania",
//        "Mauritius",
//        "Mayotte",
//        "Mexico",
//        "Micronesia",
//        "Moldova",
//        "Monaco",
//        "Mongolia",
//        "Montenegro",
//        "Montserrat",
//        "Morocco",
//        "Mozambique",
//        "Myanmar",
//        "Namibia",
//        "Nauru",
//        "Nepal",
//        "Netherlands",
//        "New-Caledonia",
//        "New-Zealand",
//        "Nicaragua",
//        "Niger",
//        "Nigeria",
//        "Niue",
//        "North-Macedonia",
//        "Norway",
//        "Oman",
//        "Pakistan",
//        "Palau",
//        "Palestine",
//        "Panama",
//        "Papua-New-Guinea",
//        "Paraguay",
//        "Peru",
//        "Philippines",
//        "Poland",
//        "Portugal",
//        "Qatar",
//        "R&eacute;union",
//        "Romania",
//        "Russia",
//        "Rwanda",
//        "S-Korea",
//        "Saint-Helena",
//        "Saint-Kitts-and-Nevis",
//        "Saint-Lucia",
//        "Saint-Martin",
//        "Saint-Pierre-Miquelon",
//        "Samoa",
//        "San-Marino",
//        "Sao-Tome-and-Principe",
//        "Saudi-Arabia",
//        "Senegal",
//        "Serbia",
//        "Seychelles",
//        "Sierra-Leone",
//        "Singapore",
//        "Sint-Maarten",
//        "Slovakia",
//        "Slovenia",
//        "Solomon-Islands",
//        "Somalia",
//        "South-Africa",
//        "South-Sudan",
//        "Spain",
//        "Sri-Lanka",
//        "St-Barth",
//        "St-Vincent-Grenadines",
//        "Sudan",
//        "Suriname",
//        "Sweden",
//        "Switzerland",
//        "Syria",
//        "Taiwan",
//        "Tajikistan",
//        "Tanzania",
//        "Thailand",
//        "Timor-Leste",
//        "Togo",
//        "Tokelau",
//        "Tonga",
//        "Trinidad-and-Tobago",
//        "Tunisia",
//        "Turkey",
//        "Turks-and-Caicos",
//        "Tuvalu",
//        "UAE",
//        "Uganda",
//        "UK",
//        "Ukraine",
//        "Uruguay",
//        "USA",
//        "Uzbekistan",
//        "Vanuatu",
//        "Vatican-City",
//        "Venezuela",
//        "Vietnam",
//        "Western-Sahara",
//        "Yemen",
//        "Zambia",
//        "Zimbabwe"
//    )
}